### ISSUE TITLE
Decide on Sync

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/rust-fragile#3]
We need to figure out the ergonomics around `Sync` for `!Sync` types. See also the conversation about it in send-cell: https://github.com/sdroege/send-cell/issues/4

**Comment by sdroege** [comment]
From my understanding it should be safe to always implement `Sync` as in the end the contained value can only ever be accessed from a single thread. What we have here conceptually is like a recursive mutex that panics if not locked from its original thread.

**Comment by mitsuhiko** [comment]
I think there is truth to this. I can't think of a reason right now why it can't be `Sync`.

**Comment by sdroege** [comment]
Do you remember why you did https://github.com/mitsuhiko/rust-fragile/commit/96f799deb258a6e2ec8db09e409e6a3f00c03246 ?

**Comment by mitsuhiko** [comment]
I wanted to release the library for public consumption and did not want to give a guarantee I cannot hold later if it turns out to be unsound.

**Comment by majewsky** [comment]
I agree that implementing Sync for arbitrary T is sound as far as Rust's soundness model goes, but I think that, with my ergonomics hat on, it goes against the spirit of Sync. The [doc for Sync](https://doc.rust-lang.org/std/marker/trait.Sync.html) says that Sync marks "types for which it is safe to share references between threads." When I have a thing that is Sync + Clone, I have the expectation that calling `.clone()` on different threads will not only be sound, but it also won't panic. That's just my general expectation for a thing that is Clone. `clone()` is not something that I would expect to ever panic, esp. when writing a generic function with a `T: Clone` bound.

What I would like is for `Fragile<T>` etc. to be Sync, but for the other trait implementations to be gated on the traits implemented by T. For example, Debug can always be implemented because it never panics, but Clone should only be implemented for `T: WrapperClone` with WrapperClone as suggested [here](https://github.com/mitsuhiko/rust-fragile/issues/1#issuecomment-405930414). I don't know what to do with Ord, Eq, and Display in this situation, but I'm not sure what the usecases for these trait implementations are.
